services:
  - type: web
    name: angular-reverse-job-board
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 14.20.0
      - key: NPM_VERSION
        value: 6.14.17
