services:
  - type: web
    name: angular-reverse-job-board
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 16.20.0
      - key: NPM_VERSION
        value: 8.19.4
